plugins {
    id 'java-library'
    id 'eclipse'
    id 'maven-publish'
    id 'checkstyle'
}

group = 'com.glencoesoftware.omero'
version = '0.7.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

repositories {
    mavenCentral()
    maven {
        name = 'Unidata'
        url = 'https://artifacts.unidata.ucar.edu/repository/unidata-releases/'
    }
    maven {
        url = 'https://artifacts.glencoesoftware.com/artifactory/ome.releases'
    }
    maven {
        url = 'https://artifacts.glencoesoftware.com/artifactory/ome.external'
    }
    maven {
        url = 'https://artifacts.glencoesoftware.com/artifactory/scijava-thirdparty'
    }
    maven {
        url = 'https://repo.glencoesoftware.com/repository/bioformats2raw2ometiff/'
    }
}

ext {
    awsSdkVersion = '2.34.6'
    jacksonVersion = '2.20.0'
    formatsVersion = '8.5.0'
}

dependencies {
    api 'org.openmicroscopy:omero-blitz:5.8.4'

    implementation "dev.zarr:zarr-java:0.1.3"

    implementation "com.fasterxml.jackson.core:jackson-core:${jacksonVersion}"
    implementation "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
    implementation "ome:formats-api:${formatsVersion}"
    implementation "ome:formats-gpl:${formatsVersion}"
    implementation "software.amazon.awssdk:aws-core:${awsSdkVersion}"
    implementation "software.amazon.awssdk:sdk-core:${awsSdkVersion}"
    implementation "software.amazon.awssdk:retries:${awsSdkVersion}"
    implementation "software.amazon.awssdk:url-connection-client:${awsSdkVersion}"
    implementation 'org.apache.tika:tika-core:1.28.5'
    implementation 'ch.qos.logback:logback-classic:1.3.14'
    implementation 'com.github.ben-manes.caffeine:caffeine:3.1.8'
    implementation 'edu.ucar:cdm-core:5.9.1'
    implementation 'org.perf4j:perf4j:0.9.16'
    implementation 'org.slf4j:slf4j-api:2.0.9'

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'info.picocli:picocli:4.7.5'
    testImplementation 'com.glencoesoftware:bioformats2raw:0.12.0'
}

test {
  useJUnit()
}

publishing {
    publications {
        omeroZarrPixelBuffer(MavenPublication) {
            from components.java
            pom {
                name = 'OMERO Zarr Pixel Buffer'
                licenses {
                    license {
                        name = 'GNU General Public License version 2'
                        url = 'http://www.gnu.org/licenses/gpl-2.0.txt'
                    }
                }
            }
        }
    }

    repositories {
        maven {
            url = 'https://artifacts.glencoesoftware.com/artifactory/gs-omero-snapshots-local/'
            credentials {
               username = project.properties.ArtifactoryUserName
               password = project.properties.ArtifactoryPassword
            }
        }
    }
}

jar {
    manifest {
        attributes(
            "Created-By": "Gradle ${gradle.gradleVersion}",
            "Build-Jdk": "${System.properties['java.version']} (${System.properties['java.vendor']} ${System.properties['java.vm.version']})",
            "Built-By": System.properties['user.name'],
            "Built-On": new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ").format(new Date()),
            "Implementation-Build": "git rev-parse --verify HEAD".execute().getText().trim(),
            "Implementation-Title": "OMERO Zarr Pixel Buffer",
            "Implementation-Version": archiveVersion,
            "Implementation-Vendor": "Glencoe Software Inc.",
        )
    }
}

checkstyle {
    toolVersion = "10.26.1"
}